
version: '3.8'
services:
  pitila:
    build: .
    container_name: pitila
    image: pitila:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pitila_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=senha123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: pitila-postgres
    environment:
      POSTGRES_DB: pitila_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: antuneschacuma@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Chacuma2890
    ports:
      - "15432:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
